'use strict';

module.exports = {

  en: {
    adjectives: [
      'beautiful', 'amazing', 'brilliant', 'fantastic', 'gorgeous', 'magnificent',
      'spectacular', 'wonderful', 'extraordinary', 'incredible', 'marvelous', 'outstanding',
      'remarkable', 'sensational', 'stunning', 'superb', 'terrific', 'tremendous',
      'admirable', 'alluring', 'appealing', 'astonishing', 'breathtaking', 'captivating',
      'charming', 'dazzling', 'delightful', 'elegant', 'enchanting', 'exquisite',
      'fabulous', 'glamorous', 'glorious', 'graceful', 'handsome', 'impressive',
      'lovely', 'majestic', 'noble', 'pleasant', 'radiant', 'ravishing',
      'resplendent', 'splendid', 'striking', 'sublime', 'delicate', 'divine',
      'dreamy', 'ethereal', 'flawless', 'heavenly', 'ideal', 'immaculate',
      'luminous', 'mesmerizing', 'opulent', 'picturesque', 'pristine', 'scenic',
      'serene', 'tantalizing', 'vibrant', 'vivid', 'wondrous', 'adorable',
      'angelic', 'beaming', 'blooming', 'bountiful', 'bright', 'cheerful',
      'colorful', 'comely', 'cute', 'dainty', 'fine', 'fresh',
      'glowing', 'grand', 'great', 'happy', 'harmonious', 'illustrious',
      'jolly', 'joyful', 'keen', 'kind', 'lively', 'magnetic',
      'neat', 'nice', 'ornate', 'polished', 'pretty', 'refined',
      'rich', 'romantic', 'shining', 'silky', 'sleek', 'smart',
      'smooth', 'soft', 'sparkling', 'sweet', 'tasteful', 'tidy',
      'trim', 'warm', 'youthful', 'zealous', 'fierce', 'bold',
      'courageous', 'daring', 'fearless', 'gallant', 'heroic', 'intrepid',
      'mighty', 'powerful', 'robust', 'stalwart', 'strong', 'valiant',
      'agile', 'athletic', 'dynamic', 'energetic', 'nimble', 'quick',
      'rapid', 'swift', 'clever', 'cunning', 'ingenious', 'sharp',
      'wise', 'witty', 'ambitious', 'determined', 'driven', 'passionate',
      'persistent', 'resolute', 'steadfast', 'tenacious', 'cozy', 'gentle'
    ],

    nouns: [
      'mountain', 'ocean', 'river', 'forest', 'desert', 'island', 'valley', 'canyon',
      'volcano', 'glacier', 'waterfall', 'meadow', 'prairie', 'tundra', 'savanna',
      'jungle', 'reef', 'lagoon', 'peninsula', 'archipelago', 'plateau', 'cliff',
      'cave', 'spring', 'stream', 'brook', 'pond', 'lake', 'sea', 'bay',
      'gulf', 'harbor', 'shore', 'beach', 'coast', 'cape', 'summit', 'peak',
      'ridge', 'slope', 'hill', 'dune', 'oasis', 'marsh', 'swamp', 'delta',
      'estuary', 'fjord', 'gorge', 'ravine', 'trench', 'basin', 'crest', 'ledge',
      'bluff', 'knoll', 'mesa', 'butte', 'geyser', 'star', 'moon', 'sun',
      'planet', 'galaxy', 'universe', 'cosmos', 'nebula', 'asteroid', 'comet',
      'meteor', 'constellation', 'aurora', 'horizon', 'atmosphere', 'crystal',
      'diamond', 'emerald', 'ruby', 'sapphire', 'pearl', 'gold', 'silver',
      'bronze', 'platinum', 'iron', 'copper', 'steel', 'titanium', 'marble',
      'granite', 'obsidian', 'quartz', 'jade', 'amber', 'ivory', 'silk',
      'velvet', 'satin', 'linen', 'cotton', 'wool', 'leather', 'lace',
      'ribbon', 'feather', 'petal', 'blossom', 'bloom', 'bud', 'seed',
      'root', 'stem', 'leaf', 'branch', 'trunk', 'bark', 'vine', 'thorn',
      'moss', 'fern', 'orchid', 'rose', 'lily', 'tulip', 'daisy', 'sunflower',
      'lotus', 'jasmine', 'lavender', 'iris', 'violet', 'poppy', 'carnation',
      'chrysanthemum', 'magnolia', 'gardenia', 'hibiscus', 'camellia', 'peony',
      'dahlia', 'marigold', 'bluebell', 'daffodil', 'kingdom', 'empire', 'castle',
      'tower', 'bridge', 'temple', 'palace', 'fortress', 'cathedral', 'monument'
    ],

    verbs: [
      'accelerate', 'accomplish', 'achieve', 'acquire', 'adapt', 'advance',
      'advocate', 'amplify', 'analyze', 'appreciate', 'ascend', 'assemble',
      'assert', 'assist', 'attract', 'awaken', 'balance', 'believe',
      'benefit', 'bloom', 'boost', 'breathe', 'build', 'calculate',
      'capture', 'celebrate', 'challenge', 'champion', 'change', 'charge',
      'cherish', 'climb', 'collaborate', 'command', 'communicate', 'compel',
      'complete', 'compose', 'conceive', 'conquer', 'consider', 'construct',
      'contemplate', 'contribute', 'control', 'convert', 'convince', 'create',
      'cultivate', 'dare', 'decide', 'declare', 'defend', 'define',
      'deliver', 'demonstrate', 'design', 'desire', 'determine', 'develop',
      'devote', 'direct', 'discover', 'distinguish', 'dominate', 'dream',
      'drive', 'elevate', 'eliminate', 'embrace', 'emerge', 'empower',
      'enable', 'encourage', 'endure', 'engage', 'engineer', 'enhance',
      'enlighten', 'enrich', 'ensure', 'envision', 'establish', 'evaluate',
      'evolve', 'examine', 'exceed', 'excel', 'exchange', 'excite',
      'execute', 'exercise', 'exhibit', 'expand', 'experience', 'experiment',
      'explore', 'express', 'extend', 'facilitate', 'fashion', 'flourish',
      'focus', 'forge', 'formulate', 'foster', 'fulfill', 'gather',
      'generate', 'govern', 'grasp', 'grow', 'guarantee', 'guide',
      'handle', 'harvest', 'honor', 'hustle', 'ignite', 'illuminate',
      'illustrate', 'imagine', 'impact', 'implement', 'improve', 'improvise',
      'incorporate', 'increase', 'influence', 'inform', 'initiate', 'innovate',
      'inspire', 'install', 'integrate', 'intensify', 'interact', 'interpret',
      'introduce', 'invent', 'investigate', 'invest', 'invoke', 'involve',
      'journey', 'launch', 'lead', 'learn', 'leverage', 'liberate',
      'maintain', 'manage', 'manifest', 'master', 'maximize', 'measure',
      'navigate', 'negotiate', 'nurture', 'observe'
    ],

    animals: [
      'lion', 'tiger', 'elephant', 'giraffe', 'zebra', 'rhinoceros', 'hippopotamus',
      'cheetah', 'leopard', 'jaguar', 'panther', 'wolf', 'fox', 'bear', 'deer',
      'moose', 'elk', 'bison', 'buffalo', 'antelope', 'gazelle', 'impala',
      'wildebeest', 'hyena', 'jackal', 'coyote', 'mongoose', 'meerkat', 'weasel',
      'otter', 'beaver', 'badger', 'raccoon', 'porcupine', 'hedgehog', 'squirrel',
      'chipmunk', 'rabbit', 'hare', 'mouse', 'rat', 'hamster', 'gerbil',
      'ferret', 'mink', 'skunk', 'opossum', 'armadillo', 'sloth', 'anteater',
      'pangolin', 'koala', 'kangaroo', 'wallaby', 'wombat', 'platypus', 'echidna',
      'gorilla', 'chimpanzee', 'orangutan', 'baboon', 'mandrill', 'lemur', 'monkey',
      'gibbon', 'macaque', 'marmoset', 'dolphin', 'whale', 'shark', 'orca',
      'narwhal', 'walrus', 'seal', 'manatee', 'octopus', 'squid', 'jellyfish',
      'starfish', 'seahorse', 'clownfish', 'swordfish', 'tuna', 'salmon', 'trout',
      'bass', 'catfish', 'pike', 'perch', 'carp', 'goldfish', 'barracuda',
      'stingray', 'eagle', 'hawk', 'falcon', 'owl', 'vulture', 'condor',
      'osprey', 'crane', 'heron', 'egret', 'pelican', 'flamingo', 'swan',
      'goose', 'duck', 'penguin', 'puffin', 'albatross', 'parrot', 'macaw',
      'cockatoo', 'parakeet', 'toucan', 'woodpecker', 'hummingbird', 'kingfisher',
      'robin', 'sparrow', 'finch', 'canary', 'cardinal', 'crow', 'raven',
      'magpie', 'dove', 'pigeon', 'peacock', 'pheasant', 'quail', 'turkey',
      'ostrich', 'emu', 'cobra', 'python', 'viper', 'anaconda', 'iguana',
      'chameleon', 'gecko', 'crocodile', 'alligator', 'turtle', 'tortoise',
      'frog', 'toad', 'salamander', 'butterfly', 'dragonfly', 'firefly',
      'ladybug', 'beetle', 'ant', 'bee', 'wasp', 'cricket', 'grasshopper'
    ],

    colors: [
      'red', 'blue', 'green', 'yellow', 'orange', 'purple', 'pink', 'black',
      'white', 'gray', 'brown', 'cyan', 'magenta', 'turquoise', 'teal', 'navy',
      'maroon', 'burgundy', 'crimson', 'scarlet', 'ruby', 'coral', 'salmon',
      'peach', 'apricot', 'tangerine', 'amber', 'gold', 'lemon', 'lime',
      'olive', 'emerald', 'jade', 'mint', 'sage', 'forest', 'chartreuse',
      'aqua', 'cerulean', 'cobalt', 'indigo', 'sapphire', 'lavender', 'violet',
      'plum', 'mauve', 'orchid', 'fuchsia', 'rose', 'blush', 'champagne',
      'cream', 'ivory', 'pearl', 'snow', 'silver', 'platinum', 'charcoal',
      'onyx', 'obsidian', 'ebony', 'jet', 'slate', 'ash', 'smoke',
      'fog', 'mist', 'cloud', 'bone', 'sand', 'tan', 'khaki',
      'beige', 'wheat', 'honey', 'caramel', 'chocolate', 'coffee', 'mocha',
      'espresso', 'mahogany', 'chestnut', 'sienna', 'rust', 'copper', 'bronze',
      'brass', 'vermilion', 'carmine', 'cerise'
    ],

    emotions: [
      'happy', 'sad', 'angry', 'excited', 'nervous', 'anxious', 'calm', 'peaceful',
      'joyful', 'content', 'grateful', 'hopeful', 'proud', 'confident', 'brave',
      'courageous', 'fearless', 'bold', 'daring', 'adventurous', 'enthusiastic',
      'passionate', 'determined', 'motivated', 'inspired', 'curious', 'fascinated',
      'amazed', 'astonished', 'surprised', 'delighted', 'thrilled', 'ecstatic',
      'euphoric', 'blissful', 'elated', 'overjoyed', 'cheerful', 'merry', 'jolly',
      'gleeful', 'upbeat', 'optimistic', 'positive', 'radiant', 'glowing', 'warm',
      'tender', 'loving', 'caring', 'compassionate', 'empathetic', 'sympathetic',
      'gentle', 'kind', 'generous', 'thoughtful', 'considerate', 'appreciative',
      'thankful', 'blessed', 'fortunate', 'lucky', 'relieved', 'relaxed', 'serene',
      'tranquil', 'composed', 'collected', 'centered', 'grounded', 'balanced',
      'harmonious', 'unified', 'whole', 'complete', 'fulfilled', 'satisfied',
      'accomplished', 'victorious', 'triumphant', 'successful', 'powerful', 'strong',
      'mighty', 'fierce', 'intense', 'fervent', 'zealous', 'devoted', 'dedicated',
      'committed', 'loyal', 'faithful', 'trustworthy', 'reliable', 'dependable',
      'steady', 'stable', 'secure', 'safe', 'comfortable', 'cozy', 'welcome',
      'accepted', 'included', 'valued', 'respected', 'admired', 'honored',
      'esteemed', 'revered', 'cherished', 'treasured', 'beloved', 'adored',
      'nostalgic', 'sentimental', 'wistful', 'melancholy', 'somber', 'pensive',
      'reflective', 'contemplative', 'meditative', 'mindful', 'aware', 'attentive',
      'focused', 'alert', 'vigilant', 'watchful', 'observant', 'perceptive'
    ],

    food: [
      'apple', 'banana', 'cherry', 'grape', 'mango', 'orange', 'peach', 'pear',
      'plum', 'strawberry', 'blueberry', 'raspberry', 'blackberry', 'cranberry',
      'watermelon', 'cantaloupe', 'honeydew', 'pineapple', 'papaya', 'kiwi',
      'coconut', 'avocado', 'pomegranate', 'fig', 'date', 'lemon', 'lime',
      'grapefruit', 'tangerine', 'mandarin', 'apricot', 'nectarine', 'guava',
      'dragonfruit', 'lychee', 'persimmon', 'starfruit', 'jackfruit', 'durian',
      'tomato', 'potato', 'carrot', 'onion', 'garlic', 'ginger', 'celery',
      'broccoli', 'cauliflower', 'spinach', 'lettuce', 'cabbage', 'kale',
      'arugula', 'radish', 'turnip', 'beet', 'cucumber', 'zucchini', 'squash',
      'pumpkin', 'eggplant', 'pepper', 'corn', 'peas', 'beans', 'lentils',
      'chickpeas', 'rice', 'wheat', 'oats', 'barley', 'quinoa', 'couscous',
      'pasta', 'noodles', 'bread', 'toast', 'bagel', 'croissant', 'muffin',
      'pancake', 'waffle', 'cereal', 'granola', 'yogurt', 'cheese', 'butter',
      'cream', 'milk', 'chocolate', 'vanilla', 'cinnamon', 'nutmeg', 'clove',
      'cardamom', 'saffron', 'turmeric', 'cumin', 'oregano', 'basil', 'thyme',
      'rosemary', 'parsley', 'cilantro', 'dill', 'mint', 'sage', 'tarragon',
      'steak', 'chicken', 'salmon', 'shrimp', 'lobster', 'crab', 'oyster',
      'sushi', 'ramen', 'pizza', 'burger', 'taco', 'burrito', 'falafel',
      'hummus', 'kebab'
    ],

    nature: [
      'sunshine', 'rainfall', 'snowfall', 'thunder', 'lightning', 'rainbow', 'breeze',
      'hurricane', 'tornado', 'tsunami', 'earthquake', 'blizzard', 'drought', 'flood',
      'storm', 'tempest', 'cyclone', 'monsoon', 'hailstorm', 'fog', 'mist', 'dew',
      'frost', 'ice', 'sleet', 'avalanche', 'mudslide', 'wildfire', 'eruption',
      'tide', 'current', 'wave', 'ripple', 'splash', 'spray', 'drizzle', 'downpour',
      'gust', 'gale', 'squall', 'whirlwind', 'zephyr', 'twilight', 'dawn', 'dusk',
      'sunrise', 'sunset', 'moonrise', 'starlight', 'moonlight', 'daylight', 'shadow',
      'shade', 'darkness', 'brightness', 'radiance', 'glow', 'shimmer', 'sparkle',
      'glitter', 'gleam', 'flash', 'flicker', 'bloom', 'blossom', 'sprout',
      'germinate', 'wilt', 'decay', 'erosion', 'sediment', 'pollen', 'nectar',
      'sap', 'resin', 'bark', 'foliage', 'canopy', 'undergrowth', 'thicket',
      'grove', 'woodland', 'clearing', 'glade', 'meadow', 'pasture', 'field',
      'prairie', 'steppe', 'tundra', 'taiga', 'rainforest', 'mangrove', 'coral',
      'reef', 'atoll', 'islet', 'shoal', 'sandbar', 'driftwood', 'seashell',
      'pebble', 'boulder', 'cobblestone', 'gravel', 'sand', 'silt', 'clay',
      'loam', 'soil', 'earth', 'terrain', 'landscape', 'horizon', 'vista',
      'panorama', 'wilderness', 'habitat', 'ecosystem', 'biome', 'wetland'
    ],

    technology: [
      'algorithm', 'application', 'bandwidth', 'binary', 'bitcoin', 'blockchain',
      'bluetooth', 'browser', 'buffer', 'byte', 'cache', 'cloud', 'codec',
      'compiler', 'cookie', 'cryptography', 'cybersecurity', 'dashboard', 'database',
      'debugging', 'decryption', 'deployment', 'developer', 'digital', 'domain',
      'download', 'drone', 'ecosystem', 'email', 'encryption', 'endpoint', 'ethernet',
      'fiber', 'firewall', 'firmware', 'framework', 'frontend', 'backend', 'fullstack',
      'gateway', 'gigabyte', 'github', 'gpu', 'graphics', 'hacker', 'hardware',
      'hashtag', 'hosting', 'html', 'http', 'hyperlink', 'icon', 'infrastructure',
      'interface', 'internet', 'intranet', 'javascript', 'kernel', 'keyboard',
      'laptop', 'latency', 'linux', 'login', 'machine', 'malware', 'markup',
      'memory', 'metadata', 'microchip', 'microprocessor', 'middleware', 'modem',
      'module', 'monitor', 'motherboard', 'multimedia', 'network', 'node',
      'notification', 'offline', 'online', 'opensource', 'operating', 'output',
      'packet', 'password', 'payload', 'phishing', 'pixel', 'platform', 'plugin',
      'podcast', 'portal', 'processor', 'programming', 'protocol', 'proxy', 'python',
      'query', 'queue', 'ram', 'ransomware', 'reboot', 'recursion', 'redirect',
      'registry', 'rendering', 'repository', 'resolution', 'responsive', 'robotics',
      'router', 'runtime', 'sandbox', 'screenshot', 'script', 'sdk', 'search',
      'server', 'silicon', 'smartphone', 'snippet', 'socket', 'software', 'source',
      'spreadsheet', 'sql', 'ssh', 'ssl', 'stack', 'startup', 'storage',
      'streaming', 'subnet', 'synchronize', 'syntax', 'tablet', 'terabyte',
      'terminal', 'thread', 'token', 'typescript', 'upload', 'url', 'usb',
      'virtual', 'virus', 'vpn', 'webapp', 'website', 'widget', 'wifi'
    ],

    space: [
      'universe', 'galaxy', 'nebula', 'supernova', 'constellation', 'asteroid', 'meteor',
      'meteorite', 'comet', 'satellite', 'orbit', 'gravity', 'blackhole', 'wormhole',
      'quasar', 'pulsar', 'magnetar', 'exoplanet', 'protostar', 'redgiant', 'whitedwarf',
      'neutrino', 'photon', 'cosmic', 'celestial', 'interstellar', 'intergalactic',
      'spacecraft', 'astronaut', 'cosmonaut', 'telescope', 'observatory', 'planetarium',
      'spacestation', 'launchpad', 'countdown', 'liftoff', 'trajectory', 'velocity',
      'acceleration', 'momentum', 'thrust', 'propulsion', 'antimatter', 'darkmatter',
      'darkenergy', 'spacetime', 'relativity', 'quantum', 'singularity', 'eclipse',
      'solstice', 'equinox', 'rotation', 'revolution', 'axis', 'apogee', 'perigee',
      'zenith', 'nadir', 'parallax', 'redshift', 'blueshift', 'spectrum', 'radiation',
      'infrared', 'ultraviolet', 'xray', 'gamma', 'solar', 'lunar', 'stellar',
      'planetary', 'galactic', 'void', 'abyss', 'infinity', 'eternity', 'dimension',
      'multiverse', 'hyperspace', 'lightspeed', 'warp', 'fusion', 'fission', 'plasma',
      'corona', 'chromosphere', 'photosphere', 'sunspot', 'solarflare', 'solarwind',
      'magnetosphere', 'ionosphere'
    ],

    music: [
      'melody', 'harmony', 'rhythm', 'tempo', 'beat', 'chord', 'note', 'scale',
      'pitch', 'tone', 'octave', 'treble', 'bass', 'alto', 'soprano', 'tenor',
      'baritone', 'crescendo', 'diminuendo', 'fortissimo', 'pianissimo', 'allegro',
      'adagio', 'andante', 'presto', 'staccato', 'legato', 'vibrato', 'fermata',
      'arpeggio', 'cadence', 'chorus', 'verse', 'bridge', 'refrain', 'intro',
      'outro', 'coda', 'prelude', 'overture', 'sonata', 'symphony', 'concerto',
      'nocturne', 'serenade', 'ballad', 'anthem', 'hymn', 'lullaby', 'requiem',
      'fugue', 'etude', 'waltz', 'minuet', 'rondo', 'suite', 'opera',
      'oratorio', 'cantata', 'aria', 'duet', 'trio', 'quartet', 'quintet',
      'ensemble', 'orchestra', 'band', 'choir', 'soloist', 'conductor', 'composer',
      'musician', 'vocalist', 'instrumentalist', 'pianist', 'guitarist', 'drummer',
      'bassist', 'violinist', 'cellist', 'flutist', 'trumpeter', 'saxophonist',
      'harmonica', 'accordion', 'banjo', 'mandolin', 'ukulele', 'harp', 'organ',
      'synthesizer', 'amplifier', 'microphone', 'speaker', 'headphone', 'equalizer',
      'reverb', 'echo', 'distortion', 'acoustic', 'electric', 'stereo', 'frequency',
      'wavelength', 'amplitude', 'resonance', 'timbre', 'dynamics', 'articulation',
      'improvisation', 'composition', 'arrangement', 'orchestration', 'transcription',
      'notation', 'clef', 'staff', 'measure', 'sharp', 'flat', 'key'
    ],

    sports: [
      'football', 'basketball', 'baseball', 'soccer', 'tennis', 'golf', 'volleyball',
      'hockey', 'cricket', 'rugby', 'boxing', 'wrestling', 'swimming', 'diving',
      'surfing', 'skiing', 'snowboarding', 'skating', 'cycling', 'running', 'jogging',
      'sprinting', 'marathon', 'triathlon', 'decathlon', 'pentathlon', 'gymnastics',
      'archery', 'fencing', 'rowing', 'sailing', 'kayaking', 'canoeing', 'climbing',
      'hiking', 'bowling', 'billiards', 'darts', 'badminton', 'squash', 'racquetball',
      'lacrosse', 'polo', 'equestrian', 'rodeo', 'motocross', 'karting', 'racing',
      'championship', 'tournament', 'league', 'match', 'game', 'set', 'round',
      'inning', 'quarter', 'half', 'overtime', 'penalty', 'foul', 'goal', 'score',
      'point', 'assist', 'rebound', 'touchdown', 'homerun', 'strikeout', 'slam',
      'ace', 'birdie', 'eagle', 'bogey', 'par', 'knockout', 'submission',
      'medal', 'trophy', 'victory', 'defeat', 'draw', 'tie',
      'record', 'athlete', 'player', 'coach', 'referee', 'umpire', 'captain',
      'goalkeeper', 'striker', 'defender', 'midfielder', 'quarterback', 'pitcher',
      'catcher', 'batter', 'receiver', 'tackle', 'guard', 'center', 'forward',
      'winger', 'fullback', 'halfback', 'sprint', 'relay', 'hurdle', 'javelin',
      'discus', 'shotput', 'longjump', 'highjump', 'polevault', 'weightlifting'
    ],

    mythology: [
      'dragon', 'phoenix', 'unicorn', 'griffin', 'pegasus', 'centaur', 'minotaur',
      'hydra', 'chimera', 'cerberus', 'kraken', 'leviathan', 'behemoth', 'basilisk',
      'gargoyle', 'golem', 'sphinx', 'siren', 'mermaid', 'werewolf', 'vampire',
      'ghost', 'spirit', 'phantom', 'specter', 'wraith', 'banshee', 'demon',
      'angel', 'fairy', 'pixie', 'elf', 'dwarf', 'gnome', 'troll', 'ogre',
      'giant', 'titan', 'cyclops', 'colossus', 'oracle', 'prophet', 'sorcerer',
      'wizard', 'witch', 'warlock', 'enchantress', 'necromancer', 'alchemist',
      'druid', 'shaman', 'paladin', 'knight', 'warrior', 'champion', 'hero',
      'legend', 'myth', 'saga', 'epic', 'quest', 'adventure', 'destiny', 'fate',
      'fortune', 'prophecy', 'curse', 'blessing', 'enchantment', 'spell', 'potion',
      'elixir', 'amulet', 'talisman', 'artifact', 'relic', 'rune', 'glyph',
      'sigil', 'portal', 'realm', 'kingdom', 'empire', 'throne', 'crown',
      'scepter', 'sword', 'shield', 'armor', 'helm', 'cloak', 'staff',
      'wand', 'orb', 'crystal', 'gem', 'jewel', 'chalice', 'grail',
      'labyrinth', 'dungeon', 'tower', 'fortress', 'citadel', 'sanctuary', 'temple',
      'shrine', 'altar', 'crypt', 'tomb', 'catacomb', 'underworld', 'heaven',
      'valhalla', 'olympus', 'avalon', 'atlantis', 'eldorado', 'utopia', 'arcadia',
      'elysium', 'nirvana'
    ],

    professions: [
      'doctor', 'engineer', 'teacher', 'lawyer', 'scientist', 'architect', 'designer',
      'developer', 'programmer', 'analyst', 'manager', 'director', 'executive',
      'president', 'officer', 'administrator', 'coordinator', 'consultant', 'advisor',
      'strategist', 'planner', 'researcher', 'professor', 'instructor', 'tutor',
      'mentor', 'counselor', 'therapist', 'psychologist', 'psychiatrist', 'surgeon',
      'physician', 'dentist', 'pharmacist', 'nurse', 'paramedic', 'firefighter',
      'detective', 'investigator', 'agent', 'diplomat', 'ambassador', 'politician',
      'senator', 'governor', 'mayor', 'judge', 'attorney', 'prosecutor', 'defender',
      'advocate', 'mediator', 'arbitrator', 'accountant', 'auditor', 'economist',
      'financier', 'banker', 'broker', 'trader', 'investor', 'entrepreneur', 'founder',
      'innovator', 'inventor', 'creator', 'artist', 'painter', 'sculptor',
      'photographer', 'filmmaker', 'producer', 'actor', 'singer', 'dancer',
      'choreographer', 'writer', 'author', 'journalist', 'editor', 'publisher',
      'reporter', 'broadcaster', 'announcer', 'anchor', 'correspondent', 'columnist',
      'critic', 'blogger', 'pilot', 'astronaut', 'navigator', 'captain', 'commander',
      'admiral', 'general', 'colonel', 'sergeant', 'lieutenant', 'marshal', 'ranger',
      'scout', 'guard', 'warden', 'inspector', 'examiner', 'surveyor', 'cartographer',
      'geologist', 'biologist', 'chemist', 'physicist', 'mathematician', 'statistician',
      'astronomer', 'meteorologist', 'oceanographer', 'ecologist', 'botanist',
      'zoologist', 'veterinarian', 'geneticist', 'microbiologist', 'neuroscientist',
      'paleontologist', 'archaeologist', 'anthropologist', 'sociologist', 'historian',
      'philosopher', 'linguist', 'translator', 'interpreter', 'librarian', 'curator'
    ],

    abstract: [
      'freedom', 'justice', 'equality', 'liberty', 'democracy', 'peace', 'harmony',
      'truth', 'wisdom', 'knowledge', 'power', 'strength', 'courage', 'honor',
      'glory', 'virtue', 'integrity', 'dignity', 'respect', 'loyalty', 'devotion',
      'faith', 'hope', 'love', 'beauty', 'grace', 'elegance', 'excellence',
      'perfection', 'infinity', 'eternity', 'immortality', 'destiny', 'fate',
      'fortune', 'chance', 'luck', 'miracle', 'wonder', 'mystery', 'magic',
      'enchantment', 'imagination', 'creativity', 'innovation', 'invention',
      'inspiration', 'aspiration', 'ambition', 'determination', 'perseverance',
      'resilience', 'endurance', 'patience', 'discipline', 'focus', 'clarity',
      'vision', 'insight', 'intuition', 'awareness', 'consciousness', 'enlightenment',
      'awakening', 'transcendence', 'transformation', 'evolution', 'revolution',
      'progress', 'growth', 'development', 'prosperity', 'abundance', 'wealth',
      'success', 'achievement', 'accomplishment', 'mastery', 'expertise', 'genius',
      'brilliance', 'intelligence', 'capability', 'potential', 'possibility',
      'opportunity', 'advantage', 'privilege', 'authority', 'influence', 'impact',
      'legacy', 'heritage', 'tradition', 'culture', 'civilization', 'society',
      'community', 'unity', 'solidarity', 'brotherhood', 'sisterhood', 'friendship',
      'companionship', 'partnership', 'alliance', 'bond', 'connection', 'relationship',
      'affinity', 'kinship', 'belonging', 'identity', 'purpose', 'meaning',
      'significance', 'importance', 'value', 'worth', 'merit', 'quality',
      'standard', 'principle', 'ideal', 'philosophy', 'belief', 'conviction',
      'commitment', 'dedication', 'passion', 'enthusiasm', 'energy', 'vitality',
      'spirit', 'soul', 'essence', 'nature', 'character', 'personality'
    ]
  },

  ar: {
    adjectives: [
      'جميل', 'رائع', 'مذهل', 'خارق', 'فاتن', 'ساحر', 'بديع', 'عظيم',
      'مبهر', 'مدهش', 'باهر', 'لامع', 'متألق', 'خلاب', 'أنيق', 'فخم',
      'راقي', 'نبيل', 'كريم', 'شجاع', 'قوي', 'صلب', 'متين', 'ثابت',
      'حكيم', 'ذكي', 'فطن', 'لبق', 'ماهر', 'بارع', 'حاذق', 'متقن',
      'سريع', 'نشيط', 'حيوي', 'مفعم', 'متحمس', 'جريء', 'مقدام', 'باسل',
      'صادق', 'أمين', 'وفي', 'مخلص', 'طيب', 'لطيف', 'حنون', 'رقيق',
      'هادئ', 'وديع', 'سالم', 'مسالم', 'صبور', 'حليم', 'رحيم', 'عطوف',
      'كبير', 'صغير', 'طويل', 'قصير', 'واسع', 'ضيق', 'عميق', 'سطحي',
      'ثقيل', 'خفيف', 'صعب', 'سهل', 'بسيط', 'معقد', 'واضح', 'غامض',
      'مشرق', 'مظلم', 'دافئ', 'بارد', 'حار', 'ناعم', 'خشن', 'رطب',
      'جاف', 'نظيف', 'طاهر', 'نقي', 'صافي', 'عذب', 'حلو', 'مر',
      'حامض', 'مالح', 'غني', 'فقير', 'سعيد', 'حزين', 'فرح', 'مبتهج',
      'متفائل', 'متشائم', 'مؤمن', 'واثق', 'متواضع', 'فخور', 'شهم', 'مهيب',
      'عريق', 'أصيل', 'نادر', 'ثمين', 'غالي', 'مميز', 'فريد', 'استثنائي',
      'خالد', 'أبدي', 'سرمدي', 'عجيب', 'غريب', 'مثير', 'ممتع', 'مسلي'
    ],

    nouns: [
      'سماء', 'أرض', 'بحر', 'نهر', 'جبل', 'صحراء', 'غابة', 'وادي',
      'جزيرة', 'شاطئ', 'بحيرة', 'شلال', 'نبع', 'عين', 'بركة', 'خليج',
      'محيط', 'قمة', 'سهل', 'تل', 'منحدر', 'كهف', 'واحة', 'مرج',
      'حقل', 'بستان', 'حديقة', 'روضة', 'غصن', 'جذع', 'ورقة', 'زهرة',
      'وردة', 'ياسمين', 'نرجس', 'بنفسج', 'لوتس', 'خزامى', 'قرنفل', 'أقحوان',
      'نخلة', 'شجرة', 'عشب', 'طحلب', 'سرخس', 'صبار', 'كرمة', 'بذرة',
      'شمس', 'قمر', 'نجم', 'كوكب', 'مجرة', 'كون', 'فضاء', 'سديم',
      'نيزك', 'مذنب', 'كسوف', 'خسوف', 'فلك', 'مدار', 'أفق', 'غلاف',
      'ذهب', 'فضة', 'نحاس', 'حديد', 'فولاذ', 'رصاص', 'قصدير', 'بلاتين',
      'ألماس', 'ياقوت', 'زمرد', 'لؤلؤ', 'مرجان', 'عقيق', 'فيروز', 'كهرمان',
      'رخام', 'جرانيت', 'بلور', 'كريستال', 'عاج', 'حرير', 'قطن', 'صوف',
      'كتان', 'مخمل', 'جلد', 'دانتيل', 'شريط', 'ريشة', 'بتلة', 'برعم',
      'جذر', 'ساق', 'لحاء', 'شوكة', 'قلعة', 'قصر', 'برج', 'جسر',
      'معبد', 'مسجد', 'كنيسة', 'كاتدرائية', 'حصن', 'سور', 'باب', 'نافذة',
      'سقف', 'عمود', 'قبة', 'منارة', 'ميناء', 'مرسى', 'سوق', 'مكتبة',
      'مدرسة', 'جامعة', 'مستشفى', 'ملعب', 'مسرح', 'متحف', 'قاعة', 'ساحة',
      'شارع', 'طريق', 'ممر', 'درب', 'زقاق', 'ميدان', 'حارة', 'مدينة',
      'قرية', 'بلدة', 'عاصمة', 'وطن', 'دولة', 'مملكة', 'إمبراطورية', 'خلافة'
    ],

    verbs: [
      'يكتب', 'يقرأ', 'يتعلم', 'يعلم', 'يفهم', 'يعرف', 'يفكر', 'يتأمل',
      'يحلم', 'يتخيل', 'يبدع', 'يبتكر', 'يخترع', 'يصمم', 'يرسم', 'ينحت',
      'يبني', 'يشيد', 'يعمر', 'يصنع', 'يطور', 'يحسن', 'يجدد', 'يغير',
      'يحول', 'ينقل', 'يسافر', 'يرحل', 'يستكشف', 'يكتشف', 'يبحث', 'ينقب',
      'يقود', 'يوجه', 'يرشد', 'يدير', 'ينظم', 'يخطط', 'يدبر', 'يحكم',
      'يقرر', 'يختار', 'يحدد', 'يعين', 'يأمر', 'ينهى', 'يطلب', 'يسأل',
      'يجيب', 'يرد', 'يتحدث', 'يتكلم', 'ينطق', 'يصرخ', 'يهمس', 'يغني',
      'يعزف', 'يرقص', 'يلعب', 'يسبح', 'يركض', 'يمشي', 'يقفز', 'يطير',
      'يحلق', 'يصعد', 'ينزل', 'يهبط', 'يسقط', 'يرتفع', 'ينمو', 'يزهر',
      'يثمر', 'يحصد', 'يزرع', 'يسقي', 'يغذي', 'يطعم', 'يشرب', 'يأكل',
      'يحب', 'يعشق', 'يهوى', 'يشتاق', 'يحن', 'يتذكر', 'ينسى', 'يسامح',
      'يغفر', 'يعفو', 'يرحم', 'يعطف', 'يساعد', 'يساند', 'يدعم', 'يشجع',
      'يحفز', 'يلهم', 'ينير', 'يضيء', 'يشع', 'يتوهج', 'يلمع', 'يبرق',
      'يدافع', 'يحمي', 'يصون', 'يحرس', 'يحارب', 'يقاتل', 'يكافح', 'يناضل',
      'ينتصر', 'يفوز', 'يتفوق', 'يبرع', 'يتميز', 'يتألق', 'ينجح', 'يحقق',
      'يصل', 'يبلغ', 'يتجاوز', 'يتخطى', 'يعبر', 'يجتاز', 'يتغلب', 'يقهر',
      'يصبر', 'يتحمل'
    ],

    animals: [
      'أسد', 'نمر', 'فيل', 'زرافة', 'حمار وحشي', 'وحيد القرن', 'فهد',
      'نمر مرقط', 'ذئب', 'ثعلب', 'دب', 'غزال', 'ظبي', 'أيل', 'جاموس',
      'ثور', 'بقرة', 'خروف', 'ماعز', 'جمل', 'حصان', 'حمار', 'بغل',
      'أرنب', 'فأر', 'جرذ', 'سنجاب', 'قنفذ', 'خلد', 'ثعلب الماء', 'قندس',
      'راكون', 'كسلان', 'قرد', 'غوريلا', 'شمبانزي', 'إنسان الغاب', 'ليمور',
      'كوالا', 'كنغر', 'خلد الماء', 'دلفين', 'حوت', 'قرش', 'حوت قاتل',
      'فقمة', 'فظ', 'خروف البحر', 'أخطبوط', 'حبار', 'قنديل البحر', 'نجم البحر',
      'فرس البحر', 'سمكة', 'تونة', 'سلمون', 'سمك السيف', 'باراكودا', 'سلحفاة',
      'تمساح', 'ضفدع', 'علجوم', 'سلمندر', 'حرباء', 'وزغة', 'إغوانا',
      'ثعبان', 'أفعى', 'كوبرا', 'بايثون', 'أناكوندا', 'نسر', 'صقر',
      'باز', 'بومة', 'نسر جريفون', 'كندور', 'لقلق', 'مالك الحزين', 'بلشون',
      'بجع', 'فلامنجو', 'بجعة', 'إوزة', 'بطة', 'بطريق', 'ببغاء', 'مكاو',
      'كوكاتو', 'طوقان', 'نقار الخشب', 'طنان', 'عصفور', 'حسون', 'كناري',
      'غراب', 'حمامة', 'يمامة', 'طاووس', 'ديك رومي', 'نعامة', 'فراشة',
      'يعسوب', 'يراعة', 'خنفساء', 'دعسوقة', 'نملة', 'نحلة', 'دبور',
      'جندب', 'صرصور', 'عنكبوت', 'عقرب', 'حريشة', 'دودة', 'حلزون',
      'محار', 'سرطان', 'جراد البحر', 'روبيان', 'قنديل', 'إسفنج', 'مرجان'
    ],

    colors: [
      'أحمر', 'أزرق', 'أخضر', 'أصفر', 'برتقالي', 'بنفسجي', 'وردي', 'أسود',
      'أبيض', 'رمادي', 'بني', 'سماوي', 'فيروزي', 'نيلي', 'كحلي', 'قرمزي',
      'عنابي', 'زهري', 'ذهبي', 'فضي', 'نحاسي', 'برونزي', 'بلاتيني', 'عاجي',
      'كريمي', 'بيج', 'رملي', 'قمحي', 'عسلي', 'كراميل', 'شوكولاتي', 'بندقي',
      'كستنائي', 'صدئ', 'زيتوني', 'نعناعي', 'زمردي', 'يشمي', 'فيروزي غامق',
      'ليموني', 'مشمشي', 'خوخي', 'مرجاني', 'سلموني', 'ياقوتي', 'توتي',
      'بنفسجي فاتح', 'أرجواني', 'وردي فاقع', 'خمري', 'كهرماني', 'لؤلؤي',
      'ثلجي', 'ضبابي', 'دخاني', 'فحمي', 'أسود حالك', 'أبيض ناصع', 'أحمر داكن',
      'أزرق فاتح', 'أخضر غامق', 'أصفر فاقع', 'برتقالي محمر', 'بنفسجي غامق',
      'وردي باهت', 'رمادي فاتح', 'رمادي داكن', 'بني فاتح', 'بني غامق',
      'أزرق سماوي', 'أزرق ملكي', 'أخضر زيتي', 'أخضر فاتح', 'أحمر ناري',
      'ذهبي لامع', 'فضي لامع', 'أسود لامع', 'أبيض كريمي', 'رمادي فولاذي'
    ],

    emotions: [
      'سعادة', 'حزن', 'غضب', 'فرح', 'حماس', 'قلق', 'خوف', 'أمان',
      'هدوء', 'سكينة', 'طمأنينة', 'سلام', 'راحة', 'رضا', 'قناعة', 'امتنان',
      'شكر', 'أمل', 'تفاؤل', 'ثقة', 'فخر', 'اعتزاز', 'كرامة', 'عزة',
      'شجاعة', 'جرأة', 'إقدام', 'بسالة', 'حب', 'عشق', 'هيام', 'وله',
      'شوق', 'حنين', 'اشتياق', 'وفاء', 'إخلاص', 'ولاء', 'تفاني', 'إيثار',
      'رحمة', 'شفقة', 'عطف', 'حنان', 'رأفة', 'لطف', 'رقة', 'حلم',
      'صبر', 'تحمل', 'مثابرة', 'إصرار', 'عزيمة', 'تصميم', 'همة', 'نشاط',
      'حيوية', 'طاقة', 'قوة', 'عظمة', 'هيبة', 'وقار', 'جلال', 'مهابة',
      'دهشة', 'ذهول', 'إعجاب', 'انبهار', 'فضول', 'حيرة', 'تعجب', 'اندهاش',
      'حماسة', 'اندفاع', 'توق', 'شغف', 'ولع', 'هوس', 'افتتان', 'انجذاب',
      'ابتهاج', 'مرح', 'بهجة', 'سرور', 'نشوة', 'غبطة', 'هناء', 'نعيم',
      'تواضع', 'خشوع', 'خضوع', 'تأمل', 'تدبر', 'تفكر', 'يقظة', 'وعي',
      'إدراك', 'بصيرة', 'حدس', 'إلهام', 'تنوير', 'صحوة', 'يقين', 'إيمان',
      'توكل', 'تسليم', 'قبول', 'رضوان', 'تسامح', 'مغفرة'
    ],

    food: [
      'تفاح', 'موز', 'كرز', 'عنب', 'مانجو', 'برتقال', 'خوخ', 'كمثرى',
      'برقوق', 'فراولة', 'توت', 'توت بري', 'بطيخ', 'شمام', 'أناناس', 'بابايا',
      'كيوي', 'جوز هند', 'أفوكادو', 'رمان', 'تين', 'تمر', 'ليمون', 'جريب فروت',
      'يوسفي', 'مشمش', 'جوافة', 'ليتشي', 'كاكا', 'دوريان', 'طماطم', 'بطاطس',
      'جزر', 'بصل', 'ثوم', 'زنجبيل', 'كرفس', 'بروكلي', 'قرنبيط', 'سبانخ',
      'خس', 'ملفوف', 'كرنب', 'جرجير', 'فجل', 'لفت', 'شمندر', 'خيار',
      'كوسا', 'قرع', 'يقطين', 'باذنجان', 'فلفل', 'ذرة', 'بازلاء', 'فاصوليا',
      'عدس', 'حمص', 'فول', 'أرز', 'قمح', 'شوفان', 'شعير', 'كينوا',
      'كسكس', 'معكرونة', 'نودلز', 'خبز', 'توست', 'كعك', 'كرواسون', 'فطيرة',
      'بان كيك', 'وافل', 'لبن', 'جبن', 'زبدة', 'قشطة', 'حليب', 'شوكولاتة',
      'فانيلا', 'قرفة', 'جوزة الطيب', 'قرنفل', 'هيل', 'زعفران', 'كركم', 'كمون',
      'زعتر', 'ريحان', 'إكليل الجبل', 'بقدونس', 'كزبرة', 'شبت', 'نعناع', 'ميرمية',
      'لحم', 'دجاج', 'سمك', 'روبيان', 'كباب', 'شاورما', 'فلافل', 'حمص بطحينة',
      'تبولة', 'فتوش', 'منسف', 'كبسة', 'مندي', 'بريان', 'مشاوي', 'شيش طاووق',
      'عسل', 'مربى', 'حلاوة', 'بقلاوة', 'كنافة', 'قطايف', 'مهلبية', 'أم علي'
    ],

    nature: [
      'شروق', 'غروب', 'فجر', 'شفق', 'ظلام', 'نور', 'ضوء', 'ظل',
      'شمس', 'قمر', 'نجوم', 'سحاب', 'غيمة', 'مطر', 'ثلج', 'برد',
      'ريح', 'عاصفة', 'إعصار', 'زلزال', 'بركان', 'تسونامي', 'فيضان', 'جفاف',
      'رعد', 'برق', 'قوس قزح', 'نسيم', 'هواء', 'عاصفة رملية', 'ضباب', 'ندى',
      'صقيع', 'جليد', 'موج', 'تيار', 'مد', 'جزر', 'رذاذ', 'طوفان',
      'زوبعة', 'هبوب', 'سيل', 'انهيار', 'ثوران', 'حمم', 'رماد', 'دخان',
      'لهب', 'شرارة', 'وهج', 'بريق', 'لمعان', 'تلألؤ', 'شعاع', 'إشراق',
      'تفتح', 'إزهار', 'نمو', 'إنبات', 'ذبول', 'تحلل', 'تآكل', 'ترسب',
      'رحيق', 'لقاح', 'عصارة', 'صمغ', 'أوراق', 'أغصان', 'جذور', 'ثمار',
      'بذور', 'تربة', 'طين', 'رمل', 'حصى', 'صخور', 'أحجار', 'معادن',
      'حفرية', 'كهف', 'ينبوع', 'واحة', 'سراب', 'أفق', 'قمة', 'سفح',
      'منحدر', 'هضبة', 'سهول', 'مراعي', 'غابة', 'أدغال', 'شعاب', 'محيط',
      'بيئة', 'محمية', 'طبيعة', 'منظر'
    ],

    technology: [
      'خوارزمية', 'تطبيق', 'برمجة', 'حاسوب', 'هاتف ذكي', 'لوحي', 'شاشة',
      'لوحة مفاتيح', 'فأرة', 'طابعة', 'ماسح', 'سماعة', 'كاميرا', 'ميكروفون',
      'معالج', 'ذاكرة', 'قرص صلب', 'بطاقة رسومات', 'لوحة أم', 'مزود طاقة',
      'نظام تشغيل', 'متصفح', 'محرك بحث', 'قاعدة بيانات', 'خادم', 'سحابة',
      'شبكة', 'إنترنت', 'واي فاي', 'بلوتوث', 'بيانات', 'تشفير', 'فك تشفير',
      'أمن سيبراني', 'جدار ناري', 'فيروس', 'برمجيات خبيثة', 'اختراق', 'حماية',
      'كلمة مرور', 'مصادقة', 'تحقق', 'نسخ احتياطي', 'استعادة', 'تحديث', 'ترقية',
      'تنزيل', 'تحميل', 'رفع', 'مشاركة', 'تخزين', 'بث', 'بودكاست', 'فيديو',
      'ذكاء اصطناعي', 'تعلم آلي', 'تعلم عميق', 'شبكة عصبية', 'روبوت', 'أتمتة',
      'بلوك تشين', 'عملة رقمية', 'واقع افتراضي', 'واقع معزز', 'إنترنت الأشياء',
      'طائرة مسيرة', 'طباعة ثلاثية', 'حوسبة كمية', 'تقنية النانو', 'طاقة متجددة',
      'برنامج', 'ملف', 'مجلد', 'رابط', 'موقع', 'صفحة', 'نطاق', 'استضافة',
      'بريد إلكتروني', 'رسالة', 'إشعار', 'تنبيه', 'واجهة', 'تصميم', 'تطوير',
      'اختبار', 'نشر', 'صيانة', 'دعم فني', 'مستودع', 'إصدار', 'ترخيص',
      'مفتوح المصدر', 'إطار عمل', 'مكتبة', 'حزمة', 'وحدة', 'دالة', 'متغير',
      'ثابت', 'كائن', 'صنف', 'واجهة برمجية'
    ],

    space: [
      'كون', 'مجرة', 'سديم', 'مستعر أعظم', 'كوكب', 'نجم', 'قمر', 'شمس',
      'كويكب', 'نيزك', 'شهاب', 'مذنب', 'قمر صناعي', 'مدار', 'جاذبية', 'ثقب أسود',
      'ثقب دودي', 'نجم زائف', 'نجم نابض', 'كوكب خارجي', 'نجم أولي', 'عملاق أحمر',
      'قزم أبيض', 'نيوترينو', 'فوتون', 'كوني', 'سماوي', 'نجمي', 'كوكبي',
      'مجري', 'فراغ', 'هاوية', 'لانهاية', 'أبدية', 'بعد', 'أكوان متعددة',
      'فضائي', 'رائد فضاء', 'تلسكوب', 'مرصد', 'قبة فلكية', 'محطة فضائية',
      'منصة إطلاق', 'عد تنازلي', 'انطلاق', 'مسار', 'سرعة', 'تسارع', 'زخم',
      'دفع', 'مادة مضادة', 'مادة مظلمة', 'طاقة مظلمة', 'زمكان', 'نسبية',
      'كمية', 'تفرد', 'كسوف', 'انقلاب', 'اعتدال', 'دوران', 'محور',
      'أوج', 'حضيض', 'سمت', 'نظير السمت', 'طيف', 'إشعاع', 'أشعة تحت حمراء',
      'أشعة فوق بنفسجية', 'أشعة سينية', 'أشعة غاما', 'اندماج', 'انشطار', 'بلازما',
      'هالة', 'بقعة شمسية', 'رياح شمسية', 'غلاف مغناطيسي'
    ],

    music: [
      'لحن', 'إيقاع', 'نغمة', 'وتر', 'مقام', 'طبقة', 'جواب', 'قرار',
      'سلم', 'دو', 'ري', 'مي', 'فا', 'صول', 'لا', 'سي',
      'أغنية', 'موسيقى', 'معزوفة', 'سيمفونية', 'كونشرتو', 'سوناتا', 'أوبرا',
      'موشح', 'قصيدة', 'مونولوج', 'ديو', 'ثلاثي', 'رباعي', 'خماسي',
      'أوركسترا', 'فرقة', 'جوقة', 'كورال', 'عازف', 'مغني', 'ملحن', 'موزع',
      'قائد أوركسترا', 'عود', 'قانون', 'ناي', 'ربابة', 'كمان', 'تشيلو',
      'كمنجة', 'قيثارة', 'جيتار', 'بيانو', 'أورغ', 'طبلة', 'دف', 'رق',
      'دربكة', 'بزق', 'سنطور', 'مزمار', 'بوق', 'ترومبيت', 'ساكسفون',
      'هارمونيكا', 'أكورديون', 'بانجو', 'ماندولين', 'يوكليلي', 'هارب', 'فلوت',
      'كلارينيت', 'أوبوا', 'باسون', 'تيوبا', 'ترومبون', 'تقسيم', 'تصفيق',
      'صدى', 'رنين', 'طنين', 'همهمة', 'صفير', 'تصفير', 'غناء', 'ترنيم',
      'ترتيل', 'تلاوة', 'أنشودة', 'نشيد', 'مارش', 'فالس', 'تانغو', 'سامبا',
      'جاز', 'بلوز', 'روك', 'بوب', 'راب', 'هيب هوب'
    ],

    sports: [
      'كرة قدم', 'كرة سلة', 'كرة طائرة', 'كرة يد', 'تنس', 'غولف', 'كريكت',
      'رجبي', 'ملاكمة', 'مصارعة', 'سباحة', 'غوص', 'ركوب أمواج', 'تزلج',
      'تزلج على الثلج', 'تزلج على الجليد', 'دراجات', 'جري', 'ركض', 'ماراثون',
      'سباق ثلاثي', 'عشاري', 'جمباز', 'رماية', 'مبارزة', 'تجديف', 'إبحار',
      'تسلق', 'مشي', 'بولينج', 'تنس الطاولة', 'ريشة طائرة', 'اسكواش', 'بولو',
      'فروسية', 'سباق خيل', 'سباق سيارات', 'كارتينج', 'بطولة', 'دوري', 'كأس',
      'مباراة', 'جولة', 'شوط', 'وقت إضافي', 'ركلة جزاء', 'خطأ', 'هدف',
      'نقطة', 'تمريرة', 'تسديدة', 'ضربة', 'رمية', 'إرسال', 'استقبال',
      'دفاع', 'هجوم', 'وسط', 'حارس مرمى', 'مهاجم', 'مدافع', 'لاعب وسط',
      'مدرب', 'حكم', 'كابتن', 'لاعب', 'رياضي', 'بطل', 'ميدالية', 'درع',
      'انتصار', 'هزيمة', 'تعادل', 'رقم قياسي', 'ذهبية', 'فضية', 'برونزية',
      'تدريب', 'تمرين', 'إحماء', 'لياقة', 'قوة', 'تحمل', 'سرعة', 'مرونة',
      'رشاقة', 'توازن', 'قفز', 'رمي', 'وثب', 'جلة', 'قرص', 'رمح',
      'قفز بالزانة', 'رفع أثقال', 'كاراتيه', 'تايكوندو', 'جودو', 'كونغ فو',
      'أيكيدو', 'سومو'
    ],

    mythology: [
      'تنين', 'عنقاء', 'وحيد القرن', 'غريفين', 'حصان مجنح', 'قنطور', 'مينوتور',
      'هيدرا', 'كايميرا', 'كراكن', 'لوياثان', 'بهيموث', 'بازيليسك', 'أبو الهول',
      'حورية', 'حورية البحر', 'مستذئب', 'مصاص دماء', 'شبح', 'روح', 'طيف',
      'جني', 'عفريت', 'مارد', 'غول', 'سعلاة', 'ملاك', 'جنية', 'قزم',
      'عملاق', 'جبار', 'وحش', 'ساحر', 'ساحرة', 'مشعوذ', 'كاهن', 'عراف',
      'نبي', 'ولي', 'حكيم', 'فارس', 'محارب', 'بطل', 'أسطورة', 'خرافة',
      'ملحمة', 'حكاية', 'قصة', 'رحلة', 'مغامرة', 'قدر', 'مصير', 'نبوءة',
      'لعنة', 'بركة', 'سحر', 'تعويذة', 'جرعة', 'إكسير', 'تميمة', 'طلسم',
      'أثر', 'رمز', 'بوابة', 'عالم', 'مملكة', 'عرش', 'تاج', 'صولجان',
      'سيف', 'درع', 'خوذة', 'عباءة', 'عصا', 'جوهرة', 'كأس مقدسة',
      'متاهة', 'زنزانة', 'قلعة', 'حصن', 'معبد', 'ضريح', 'مذبح', 'سرداب',
      'عالم سفلي', 'جنة', 'فردوس', 'أطلانتس', 'شانغري لا', 'يوتوبيا',
      'فالهالا', 'أوليمبوس', 'نيرفانا'
    ],

    professions: [
      'طبيب', 'مهندس', 'معلم', 'محامي', 'عالم', 'معماري', 'مصمم', 'مبرمج',
      'محلل', 'مدير', 'رئيس', 'مسؤول', 'منسق', 'مستشار', 'مخطط', 'باحث',
      'أستاذ', 'مدرس', 'معلم خصوصي', 'مرشد', 'مستشار نفسي', 'معالج', 'طبيب نفسي',
      'جراح', 'طبيب أسنان', 'صيدلي', 'ممرض', 'مسعف', 'إطفائي', 'محقق',
      'عميل', 'دبلوماسي', 'سفير', 'سياسي', 'قاضي', 'نائب', 'وزير', 'حاكم',
      'محاسب', 'مدقق', 'اقتصادي', 'مصرفي', 'سمسار', 'تاجر', 'مستثمر',
      'رائد أعمال', 'مؤسس', 'مخترع', 'مبدع', 'فنان', 'رسام', 'نحات',
      'مصور', 'مخرج', 'منتج', 'ممثل', 'مغني', 'راقص', 'مصمم رقصات',
      'كاتب', 'مؤلف', 'صحفي', 'محرر', 'ناشر', 'مراسل', 'مذيع', 'معلق',
      'ناقد', 'مدون', 'طيار', 'رائد فضاء', 'ملاح', 'قبطان', 'قائد',
      'أميرال', 'جنرال', 'عقيد', 'رقيب', 'ملازم', 'حارس', 'مفتش',
      'مساح', 'جيولوجي', 'عالم أحياء', 'كيميائي', 'فيزيائي', 'رياضي',
      'فلكي', 'أرصادي', 'عالم بيئة', 'عالم نبات', 'عالم حيوان', 'طبيب بيطري',
      'عالم آثار', 'عالم اجتماع', 'مؤرخ', 'فيلسوف', 'لغوي', 'مترجم',
      'أمين مكتبة', 'أمين متحف', 'خطاط', 'حداد', 'نجار', 'بناء',
      'سباك', 'كهربائي', 'ميكانيكي', 'خياط', 'طباخ', 'خباز', 'حلاق', 'صائغ'
    ],

    abstract: [
      'حرية', 'عدالة', 'مساواة', 'ديمقراطية', 'سلام', 'انسجام', 'حقيقة',
      'حكمة', 'معرفة', 'علم', 'قوة', 'شجاعة', 'شرف', 'مجد', 'فضيلة',
      'نزاهة', 'كرامة', 'احترام', 'ولاء', 'إخلاص', 'إيمان', 'أمل', 'حب',
      'جمال', 'أناقة', 'تميز', 'كمال', 'لانهاية', 'أبدية', 'خلود',
      'قدر', 'مصير', 'حظ', 'معجزة', 'عجب', 'غموض', 'سحر', 'خيال',
      'إبداع', 'ابتكار', 'اختراع', 'إلهام', 'طموح', 'تصميم', 'مثابرة',
      'صمود', 'صبر', 'انضباط', 'تركيز', 'وضوح', 'رؤية', 'بصيرة', 'حدس',
      'وعي', 'إدراك', 'تنوير', 'صحوة', 'تحول', 'تطور', 'ثورة', 'تقدم',
      'نمو', 'تنمية', 'ازدهار', 'وفرة', 'ثروة', 'نجاح', 'إنجاز', 'تحقيق',
      'إتقان', 'خبرة', 'عبقرية', 'ذكاء', 'قدرة', 'إمكانية', 'فرصة',
      'سلطة', 'تأثير', 'إرث', 'تراث', 'تقاليد', 'ثقافة', 'حضارة', 'مجتمع',
      'وحدة', 'تضامن', 'أخوة', 'صداقة', 'شراكة', 'تحالف', 'رابطة', 'علاقة',
      'انتماء', 'هوية', 'غاية', 'معنى', 'أهمية', 'قيمة', 'جودة', 'مبدأ',
      'مثالية', 'فلسفة', 'عقيدة', 'التزام', 'شغف', 'حماس', 'روح', 'جوهر'
    ]
  }

};
